sudo: required
before_install:
    - sudo add-apt-repository -y ppa:fish-shell/release-2
    - sudo apt-get update
    - sudo apt-get -y install fish
    - curl -Lo ~/.config/fish/functions/fisher.fish --create-dirs git.io/fisher
script:
    - fish -c 'fisher add Dietr1ch/config-fish'
